db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=employee_db;encrypt=true;trustServerCertificate=true;
db.username=app_user
db.password=1234
