db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=${DB_URL:jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=employee_db;encrypt=true;trustServerCertificate=true}
db.username=${DB_USER:app_user}
db.password=${DB_PASSWORD:1234}
