package springmvc.model;

public enum Position {

    INTERN,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER,
    TECHNICAL_LEAD,
    ENGINEERING_MANAGER,
    CEO,
    MANAGER,
    ANALYST,
    QA_TESTER,
    HR_EXECUTIVE,
    PRODUCT_MANAGER,
    DATA_ANALYST,
    SCRUM_MASTER,
    DEVOPS_ENGINEER,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    DATABASE_ADMIN,
    SYSTEMS_ANALYST,
    MARKETING_LEAD,
    SUPPORT_ENGINEER,
    CONTENT_WRITER,
    SALES_EXECUTIVE,
    OPERATIONS_MANAGER,
    SECURITY_ANALYST,
    TECHNICAL_WRITER

}
